/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionsSectionIdRouteImport } from './routes/sections.$sectionId'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes_.$recipeId.edit'
import { Route as ImgImageIdSizeRouteImport } from './routes/img.$imageId.$size'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsSectionIdRoute = SectionsSectionIdRouteImport.update({
  id: '/sections/$sectionId',
  path: '/sections/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes_/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgImageIdSizeRoute = ImgImageIdSizeRouteImport.update({
  id: '/img/$imageId/$size',
  path: '/img/$imageId/$size',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/sections/$sectionId': typeof SectionsSectionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/img/$imageId/$size': typeof ImgImageIdSizeRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/sections/$sectionId': typeof SectionsSectionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/img/$imageId/$size': typeof ImgImageIdSizeRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/sections/$sectionId': typeof SectionsSectionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/img/$imageId/$size': typeof ImgImageIdSizeRoute
  '/recipes_/$recipeId/edit': typeof RecipesRecipeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/login'
    | '/profile'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/sections/$sectionId'
    | '/api/auth/$'
    | '/img/$imageId/$size'
    | '/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/login'
    | '/profile'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/sections/$sectionId'
    | '/api/auth/$'
    | '/img/$imageId/$size'
    | '/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/login'
    | '/profile'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/sections/$sectionId'
    | '/api/auth/$'
    | '/img/$imageId/$size'
    | '/recipes_/$recipeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  SectionsSectionIdRoute: typeof SectionsSectionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ImgImageIdSizeRoute: typeof ImgImageIdSizeRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/$sectionId': {
      id: '/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/sections/$sectionId'
      preLoaderRoute: typeof SectionsSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$recipeId/edit': {
      id: '/recipes_/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$imageId/$size': {
      id: '/img/$imageId/$size'
      path: '/img/$imageId/$size'
      fullPath: '/img/$imageId/$size'
      preLoaderRoute: typeof ImgImageIdSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  SectionsSectionIdRoute: SectionsSectionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ImgImageIdSizeRoute: ImgImageIdSizeRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
